level0 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"About This Help Sample",null,false,false,null,null,"","../../portfolio/RivioHelp/source/about.htm","content",false);
addItem(level0);
level0 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Help Contents",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Contents_en_US.htm","content",false);
addItem(level0);
level0 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Quick Views and Calendar",null,false,false,null,null,"","../../portfolio/RivioHelp/source/calendar_About_en_US.htm","content",false);
addItem(level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"About My Company Quick View",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_company_About_My_Company_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"About My Work Quick View",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_work_About_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"About the Calendar",null,false,false,null,null,"","../../portfolio/RivioHelp/source/calendar_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Today",null,false,false,null,null,"","../../portfolio/RivioHelp/source/calendar_Viewing_Today_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing a Specific Day",null,false,false,null,null,"","../../portfolio/RivioHelp/source/calendar_Viewing_Specific_Day_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding an Event",null,false,false,null,null,"","../../portfolio/RivioHelp/source/calendar_Adding_Event_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Setting an Event Reminder",null,false,false,null,null,"","../../portfolio/RivioHelp/source/calendar_Setting_Event_Reminder_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting an Event",null,false,false,null,null,"","../../portfolio/RivioHelp/source/calendar_Deleting_Event_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Notification Options",null,false,false,null,null,"","../../portfolio/RivioHelp/source/calendar_Notification_Options_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Repreating Options",null,false,false,null,null,"","../../portfolio/RivioHelp/source/calendar_Repeating_Options_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"About Company Announcements",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_company_About_Company_Announcements_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Company Announcement",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_company_Adding_Company_Announcement_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Company Announcement",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_company_Modifying_Company_Announcement_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Publishing a Company Announcement",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_company_Publishing_Company_Announcement_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting a Company Announcement",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_company_Deleting_Company_Announcement_en_US.htm","content",true);
addItem(level2,level1);
level0 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"To Dos",null,false,false,null,null,"","../../portfolio/RivioHelp/source/to_dos_About_en_US.htm","content",false);
addItem(level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a To Do",null,false,false,null,null,"","../../portfolio/RivioHelp/source/to_dos_Adding_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a To Do",null,false,false,null,null,"","../../portfolio/RivioHelp/source/to_dos_Modifying_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Marking a To Do as Done",null,false,false,null,null,"","../../portfolio/RivioHelp/source/to_dos_Marking_Done_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Tasks",null,false,false,null,null,"","../../portfolio/RivioHelp/source/tasks_Overview_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Task",null,false,false,null,null,"","../../portfolio/RivioHelp/source/tasks_Adding_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Task",null,false,false,null,null,"","../../portfolio/RivioHelp/source/tasks_Modifying_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Forwarding a Task",null,false,false,null,null,"","../../portfolio/RivioHelp/source/tasks_Forwarding_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Canceling a Task",null,false,false,null,null,"","../../portfolio/RivioHelp/source/tasks_Canceling_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Archiving a Task",null,false,false,null,null,"","../../portfolio/RivioHelp/source/tasks_Archiving_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Reopening a Task",null,false,false,null,null,"","../../portfolio/RivioHelp/source/tasks_Reopening_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Checklists",null,false,false,null,null,"","../../portfolio/RivioHelp/source/checklists_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Checking Off Sub-tasks in Checklists",null,false,false,null,null,"","../../portfolio/RivioHelp/source/checklists_Working_with_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Blank Checklist",null,false,false,null,null,"","../../portfolio/RivioHelp/source/checklists_Adding_Blank_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Checklist from a Template",null,false,false,null,null,"","../../portfolio/RivioHelp/source/checklists_Adding_from_Template_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Checklist",null,false,false,null,null,"","../../portfolio/RivioHelp/source/checklists_Modifying_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Completeing a Checklist",null,false,false,null,null,"","../../portfolio/RivioHelp/source/checklists_Completing_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Checklist Templates",null,false,false,null,null,"","../../portfolio/RivioHelp/source/checklists_Templates_en_US.htm","content",false);
addItem(level2,level1);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Creating a Checklist Template",null,false,false,null,null,"","../../portfolio/RivioHelp/source/checklists_Creating_Template_en_US.htm","content",false);
addItem(level3,level2);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying an Existing Checkliat Template",null,false,false,null,null,"","../../portfolio/RivioHelp/source/checklists_Modifying_Existing_Template_en_US.htm","content",true);
addItem(level3,level2);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Time Sheets",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_sheets_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Time Sheet",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_sheets_Adding_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Entering Hours in a Time Sheet",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_sheets_Entering_Hours_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Time Sheet",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_sheets_Modifying_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Submitting a Time Sheet for Approval",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_sheets_Submitting_for_Approval_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Approving a Time Sheet",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_sheets_Approving_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Declining a Time Sheet",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_sheets_Declining_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Printing a Time Sheet",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_sheets_Printing_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Invoices",null,false,false,null,null,"","../../portfolio/RivioHelp/source/invoices_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding an Invoice",null,false,false,null,null,"","../../portfolio/RivioHelp/source/invoices_Adding_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying an Invoice",null,false,false,null,null,"","../../portfolio/RivioHelp/source/invoices_Modifying_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Submitting an Invoice for Approval",null,false,false,null,null,"","../../portfolio/RivioHelp/source/invoices_Submitting_for_Approval_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Approving an Invoice",null,false,false,null,null,"","../../portfolio/RivioHelp/source/invoices_Approving_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Declining an Invoice",null,false,false,null,null,"","../../portfolio/RivioHelp/source/invoices_Declining_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Sending an Invoice to a Client",null,false,false,null,null,"","../../portfolio/RivioHelp/source/invoices_Sending_to_Client_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Printing an Invoice",null,false,false,null,null,"","../../portfolio/RivioHelp/source/invoices_Printing_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Setting Up Invoice Numbering",null,false,false,null,null,"","../../portfolio/RivioHelp/source/invoices_Setting_Up_Numbering_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Expense Reports",null,false,false,null,null,"","../../portfolio/RivioHelp/source/expense_reports_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding an Expense Report",null,false,false,null,null,"","../../portfolio/RivioHelp/source/expense_reports_Adding_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying an Expense Report",null,false,false,null,null,"","../../portfolio/RivioHelp/source/expense_reports_Modifying_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Submitting an Expense Report for Approval",null,false,false,null,null,"","../../portfolio/RivioHelp/source/expense_reports_Submitting_for_Approval_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Approving an Expense Report",null,false,false,null,null,"","../../portfolio/RivioHelp/source/expense_reports_Approving_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Declining an Expense Report",null,false,false,null,null,"","../../portfolio/RivioHelp/source/expense_reports_Declining_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Paying an Expense Report",null,false,false,null,null,"","../../portfolio/RivioHelp/source/expense_reports_Paying_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Printing an Expense Report",null,false,false,null,null,"","../../portfolio/RivioHelp/source/expense_reports_Printing_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Saving an Expense Report as a Local File",null,false,false,null,null,"","../../portfolio/RivioHelp/source/expense_reports_Saving_as_Local_File_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Expense Report Statuses",null,false,false,null,null,"","../../portfolio/RivioHelp/source/expense_reports_Statuses_en_us.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Time-Off Requests",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_off_requests_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Time-Off Request",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_off_requests_Adding_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Tine-Off Request",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_off_requests_Modifying_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Submitting a Time-Off Request for Approval ",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_sheets_Submitting_for_Approval_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Approving a Time-Off Request",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_off_requests_Approving_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Declining a Time-Off Request",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_off_requests_Declining_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Reopening a Time-Off Request",null,false,false,null,null,"","../../portfolio/RivioHelp/source/time_off_requests_Reopening_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Purchase Requests",null,false,false,null,null,"","../../portfolio/RivioHelp/source/purchase_requests_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Purchase Request",null,false,false,null,null,"","../../portfolio/RivioHelp/source/purchase_requests_Adding_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Purchase Request",null,false,false,null,null,"","../../portfolio/RivioHelp/source/purchase_requests_Modifying_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Submitting a Purchase Request for Approval",null,false,false,null,null,"","../../portfolio/RivioHelp/source/purchase_requests_Submitting_for_Approval_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Approving a Purchase Request",null,false,false,null,null,"","../../portfolio/RivioHelp/source/purchase_requests_Approving_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Declining a Purchase Request",null,false,false,null,null,"",null,"content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Setting Task Options",null,false,false,null,null,"","../../portfolio/RivioHelp/source/tasks_Setting_Options_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Task History",null,false,false,null,null,"","../../portfolio/RivioHelp/source/tasks_Viewing_History_en_US.htm","content",true);
addItem(level1,level0);
level0 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"My Profile",null,false,false,null,null,"",null,"content",false);
addItem(level0);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Personal Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/MyProfile_About_Personal_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying Personal Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/MyProfile_Personal_Info_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying Work Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/MyProfile_Work_Info_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Dependent",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Adding_Dependent_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying Dependent Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Modifying_Dependent_Information_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting a Dependent",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Deleting_Dependent_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding an Emergency Contact",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Adding_Emergency_Contact_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying Emergency Contact Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Modifying_Emergency_Contact_Information_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting an Emergency Contact",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Deleting_Emergency_Contact_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Payroll Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_About_Payroll_Information_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Earnings",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Viewing_Earnings_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Deductions",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Viewing_Deductions_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying W-4",null,false,false,null,null,"","../../portfolio/RivioHelp/source/MyProfile_W4_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Changing Your User ID",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Changing_Your_User_ID_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Changing Your Password",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Changing_Your_Password_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Changing Your Secret Question",null,false,false,null,null,"","../../portfolio/RivioHelp/source/my_profile_Changing_Your_Secret_Question_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"My Profile Setup",null,false,false,null,null,"","../../portfolio/RivioHelp/source/MyProfile_Setup_en_US.htm","content",true);
addItem(level1,level0);
level0 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Company Info",null,false,false,null,null,"",null,"content",false);
addItem(level0);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Company Profile",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Company_About_Company_Profile_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying Company Profile",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Company_Modify_Company_Profile_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Company Address(es)",null,false,false,null,null,"","../../portfolio/RivioHelp/source/locations_About_Company_en_US.htm","content",false);
addItem(level2,level1);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Company Address",null,false,false,null,null,"","../../portfolio/RivioHelp/source/locations_Adding_Company_en_US.htm","content",false);
addItem(level3,level2);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Company Address",null,false,false,null,null,"","../../portfolio/RivioHelp/source/locations_Modifying_Company_en_US.htm","content",false);
addItem(level3,level2);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting a Company Address",null,false,false,null,null,"","../../portfolio/RivioHelp/source/locations_Deleting_Company_en_US.htm","content",true);
addItem(level3,level2);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Events",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_company_About_Company_Events_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Company Event",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_company_Adding_Company_Event_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Company Event",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_company_Modifying_Company_Event_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting a Company Event",null,false,false,null,null,"","../../portfolio/RivioHelp/source/quick_view_my_company_Deleting_Company_Event_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Organization Chart",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Company_About_Organization_Chart_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing the Organization Chart",null,false,false,null,null,"","../../portfolio/RivioHelp/source/company_Viewing_Org_Chart_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Job Roles",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Company_Job_Roles_Search_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Searching Job Roles",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Company_Job_Roles_Search_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Employee Directory",null,false,false,null,null,"","../../portfolio/RivioHelp/source/employee_directory_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying an Employee's Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/employee_directory_Modifying_Employees_Information_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Sorting the Employee List",null,false,false,null,null,"","../../portfolio/RivioHelp/source/employee_directory_Sorting_Employee_List_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Employee Details",null,false,false,null,null,"","../../portfolio/RivioHelp/source/employee_directory_Viewing_Employee_Details_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Employee Locator",null,false,false,null,null,"","../../portfolio/RivioHelp/source/employee_locator_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Emmployees Who Are Out of the Office",null,false,false,null,null,"","../../portfolio/RivioHelp/source/employee_locator_Viewing_Employees_Out_of_Office_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Job Postings",null,false,false,null,null,"","../../portfolio/RivioHelp/source/job_postings_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing the Job Posting Liat",null,false,false,null,null,"","../../portfolio/RivioHelp/source/job_postings_Viewing__List_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Job Posting Details",null,false,false,null,null,"","../../portfolio/RivioHelp/source/job_postings_Viewing_Details_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Job Posting",null,false,false,null,null,"","../../portfolio/RivioHelp/source/job_postings_Adding_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Job Posting",null,false,false,null,null,"","../../portfolio/RivioHelp/source/job_postings_Modifying_Job_Posting_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting a Job Posting",null,false,false,null,null,"","../../portfolio/RivioHelp/source/job_postings_Deleting_en_US.htm","content",true);
addItem(level2,level1);
level0 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Employee Records",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_About_Records_ADMIN_en_US.htm","content",false);
addItem(level0);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Employee Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Employee_List_ADMIN_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding an Employee",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Add_Employee_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying an Employee's Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hremprecords_Modifying_Employees_Information_SA_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Including Employees on the Payroll List",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hremprecords_Including_Employees_Payroll_List_SA_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Searching for an Employee",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hremprecords_Searching_Employee_SA_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"About the Emplyee Information Tabs",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_About_Tabs_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Addinf or Modifying Dependent Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Dependent_Info_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Using the Dependents List",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Dependents_List_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding or Modifying Emergency Contacts Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Emergency_Info_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Using the Emergency Contacts List",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Emergency_List_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding or Modifying Employee Pay Rate Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Employee_Compensation_Info_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Addinf or Modifying Employee Employment Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Employee_Employment_Info_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding or Modifying Employee Personal Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Employee_Personal_Info_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding or Modifying Employee Work Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Employee_Work_Info_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Creating an Employee Report",null,false,false,null,null,"","../../portfolio/RivioHelp/source/HREmpRecords_Create_Employee_Report_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Reviews",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hremprec_About_Compensation_Review_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Reviews",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hremprec_Viewing_Compensation_Review_ADMIN_en_US.htm","content",false);
addItem(level3,level2);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Review",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hremprec_Adding_Compensation_Review_ADMIN_en_US.htm","content",false);
addItem(level3,level2);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Review",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hremprec_Modifying_Compensation_Review_ADMIN_en_US.htm","content",false);
addItem(level3,level2);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting a Review",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hremprec_Deleting_Compensation_Review_ADMIN_en_US.htm","content",false);
addItem(level3,level2);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Review Details",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hremprec_Compensation_Review_Details_ADMIN_en_US.htm","content",true);
addItem(level3,level2);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Employee Payroll Records",null,false,false,null,null,"","../../portfolio/RivioHelp/source/employee_records_About_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Employee Payroll Details",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Viewing_Employees_Payroll_Details_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying Employee Payroll Details",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Modifying_Employees_Payroll_Details_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Reports",null,false,false,null,null,"",null,"content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Creating Custom Reports",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hrreports_Creating_Custom_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Report Contents",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hrreports_Report_Contents_ADMIN_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Setup",null,false,false,null,null,"",null,"content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"System Reminders",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hrsetup_About_System_Reminders_ADMIN_en_US.htm","content",false);
addItem(level2,level1);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Enabling System Reminders",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hrsetup_Enabling_System_Reminders_ADMIN_en_US.htm","content",false);
addItem(level3,level2);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying the Time System Reminders are Sent",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hrsetup_Modifying_Time_System_Reminder_Sent_ADMIN_en_US.htm","content",false);
addItem(level3,level2);
level3 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Disabling System Reminders",null,false,false,null,null,"","../../portfolio/RivioHelp/source/hrsetup_Disabling_System_Reminders_ADMIN_en_US.htm","content",true);
addItem(level3,level2);
level0 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Payroll",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_About_Processing_en_US.htm","content",false);
addItem(level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Creating a New Payroll",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Creating_New_PR_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Approving a Payroll",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Approving_PR_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing or Printing a Previously Created Payroll",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Viewing_or_Printing_Previously_Created_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Changing a Payroll Check Date",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Changing_Check_Date_PR_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Archiving a Payroll",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Archiving_PR_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting a Payroll",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Deleting_PR_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Payroll Setup",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_About_Setup_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Setting Up Pay Schedules",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Setting_Up_Pay_Schedules_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Existing Pay Schedules",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Viewing_Existing_Pay_Schedule_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Pay Schedule",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Modifying_Pay_Schedule_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Setting Up Earning Types",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Setting_Up_Earning_Types_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying Earning Tyeps",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Modifying_Earning_Types_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting an Earning Types",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Deleting_an_Earning_Type_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding Deduction Types",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Adding_Deduction_Types_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying Deduction Types",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Modifying_Deduction_Types_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting Deduction Types",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Deleting_Deduction_Type_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Earning Types Detail",null,false,false,null,null,"","../../portfolio/RivioHelp/source/payroll_Earning_Types_Detail_en_US.htm","content",true);
addItem(level2,level1);
level0 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Company Policies",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Policies_About_en_US.htm","content",false);
addItem(level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Policies",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Policies_Viewing_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding Policies",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Policies_Adding_SA_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying Policies",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Policies_Modifying_SA_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting Policies",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Policies_Deleting_SA_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Procedures",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Procedures_Viewing_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding Procedures",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Procedures_Adding_SA_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying Procedures",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Procedures_Modifying_SA_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Deleting Procedures",null,false,false,null,null,"","../../portfolio/RivioHelp/source/Procedures_Deleting_SA_en_US.htm","content",true);
addItem(level1,level0);
level0 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Forms &amp; Tools",null,false,false,null,null,"","../../portfolio/RivioHelp/source/forms_tools_About_en_US.htm","content",false);
addItem(level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing a Form",null,false,false,null,null,"","../../portfolio/RivioHelp/source/forms_tools_Viewing_Form_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Form",null,false,false,null,null,"","../../portfolio/RivioHelp/source/forms_tools_Modifying_Form_en_US.htm","content",false);
addItem(level1,level0);
level1 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Saving a Form",null,false,false,null,null,"","../../portfolio/RivioHelp/source/forms_tools_Saving_Form_en_US.htm","content",true);
addItem(level1,level0);
level0 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Accounting",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_About_Area_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level0);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Account List",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_About_Account_List_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Account Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Viewing_Information_AGQBADMIN_AGADMIN-en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding an Account",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Adding_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Subaccount",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Adding_Subaccount_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying an Account",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Modifying_Account_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Hiding Inactive Accounts",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Hiding_Inactive_AGQBADMIN_AGADMIN_en_us.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Showing All Accounts",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Showing_All_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Setting an Account to Active Status",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Setting_to_Active_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Setting an Account to Inactive Status",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Setting_to_Inactive_AGQBADMIN_AGADMIN_en_US.htm","content",true);
addItem(level2,level1);
level1 = new Item("bookstyle/bookc.gif","bookstyle/booko.gif",null,null,16,16,"Customer List",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_About_Customer_List_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level1,level0);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Viewing Customer or Project Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Viewing_Cust_Proj_Info_AGQBADMIN_AGADMIN_en.US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Customer",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Adding_Customer_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Customer's Information",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Modifying_Customers_Info_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Customer Detail",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Customer_Detail_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Adding a Project",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Adding_Project_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Modifying a Project",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Modifying_Project_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Project Detail",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Project_Detail_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Hiding Inactive Customers and Projects",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Hiding_Inactive_Cust_Proj_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Setting a Customer or Project to Active",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Set_Cust_Project_Active_AGQBADMIN_AGADMIN_en_US.htm","content",false);
addItem(level2,level1);
level2 = new Item("bookstyle/qustmk.gif",null,null,null,16,16,"Setting a Customer or Project to Inactive",null,false,false,null,null,"","../../portfolio/RivioHelp/source/account_Set_Cust_Project_Inactive_AGQBADMIN_AGADMIN_en_US.htm","content",true);
addItem(level2,level1);
renderSitemap("LIST", false, null, null, null, "surfmapjs/");